### ISSUE TITLE
declare -A is not a valid flag in bash on Mac OSX

### ISSUE THREAD

**Issue by tandrewnichols** [niterain/neo4j-instance#1]
I get the following when I run commands in this binary:

```
/Users/AndrewNichols/bin/neo4j-instance: line 339: declare: -A: invalid option
```

I _believe_ the equivalent on Mac is `-a`. Maybe you can detect the OS?

The output of `help declare` on my computer is:

```
declare: declare [-afFirtx] [-p] [name[=value] ...]
    Declare variables and/or give them attributes.  If no NAMEs are
    given, then display the values of variables instead.  The -p option
    will display the attributes and values of each NAME.

    The flags are:

      -a        to make NAMEs arrays (if supported)
      -f        to select from among function names only
      -F        to display function names (and line number and source file name if
        debugging) without definitions
      -i        to make NAMEs have the `integer' attribute
      -r        to make NAMEs readonly
      -t        to make NAMEs have the `trace' attribute
      -x        to make NAMEs export

    Variables with the integer attribute have arithmetic evaluation (see
    `let') done when the variable is assigned to.

    When displaying values of variables, -f displays a function's name
    and definition.  The -F option restricts the display to function
    name only.

    Using `+' instead of `-' turns off the given attribute instead.  When
    used in a function, makes NAMEs local, as with the `local' command.
```

**Comment by niterain** [comment]
Hi Andrew:

I have fixed the array declaration, it should now work as intended.  Could you please test it out.

Best regards

**Comment by niterain** [comment]
Started up a mac instance to test out the changes.  It appears this is because of the version you are using version 3.x, associate arrays were added in bash 4.0+.  So to fix this issue, you will need to upgrade to bash4+.  I hope that helps.

**Comment by tandrewnichols** [comment]
Ok, thanks. I will give it a try.

**Comment by tandrewnichols** [comment]
So a little more feedback. First, you are correct that the bash version has something to do with it. If I disable your version check, every message logs with `\e[1;33m`, which is the last color declared, so it is apparently not treating that as an associative array. I'm in the process of trying to update to bash 4 (see [this question](http://apple.stackexchange.com/questions/221918/why-i-am-unable-to-switch-bash-to-the-one-installed-by-homebrew) - and if you have an answer, please let me know).

I still suspect that Mac will require `-a` and not `-A`, but I'll wait to confirm. Also, `\e` doesn't work with `echo -e` on Mac. Both `\033` and `\x1B` do however.

**Comment by niterain** [comment]
I am using iTerm, on Yosemite.  I have responded in StackOverflow, this is how you would update bash using brew, it worked for me.

This is it working in ITerm2, but I also checked the colors also work in the terminal that comes with MacOSX however the white background will need to change.

https://drive.google.com/open?id=0B9FOfXOBuaJxaERjbzZKb3YxcGc

**Comment by tandrewnichols** [comment]
Ok, yeah, it appears that `\e` works in terminal, but I use tmux and it does _not_ work there. I've got mine working with some edits. Might just make it available as a fork, since being on bash 3.x is likely to be a common problem for Mac users. Or I can open a PR to add it as a separate script if you'd be interested in making it part of this.
